### ISSUE TITLE
citing?

### ISSUE THREAD

**Issue by aromanowski** [NicolasH2/ggdendroplot#4]
Hi Nicolas,
Is there a specific way to cite this package?

Thanks,
Andres

**Comment by NicolasH2** [comment]
Hi @aromanowski ,sorry for the late reply. I assume by this point it does not matter anymore, but for the record you can cite the package like this:

Huber N (2023). ggdendroplot: Dendrograms for ggplot. R package version 0.1.0, <https://github.com/NicolasH2/ggdendroplot>.
